#!/usr/bin/python3

from bs4 import BeautifulSoup
import openpyxl
import re


#Globals

CURRENT_TABLE_FILE = "./Nutrition.xlsx"
NEW_TABLE_FILE = "nutrition_new.xlsx"

NUTRITION_VALUES={
	"C" : ["units", "small"],
	"D" : ["energy","energie"],
	"E" : ["fat", "fett"],
	"_E" : ["saturated fatty", "gesättigte Fettsäuren"],
	"F" : ["carbohydrates", "Kohlenhydrate"],
	"_F" : ["of which sugars"],
	"G" : ["fibres", "ballaststoffe"],
	"H" : ["protein"],
	"I" : ["salt", "salz"],
	"J" : ["magnesium"],
	"K" : ["creatine"]
}


#def parseNutritionData(nutrition_data, cell):
#	for i in nutrition_data:


def ExtractNutrition(html):
	nutrition_html = BeautifulSoup(html, 'html.parser')
	nutrition_table = nutrition_html.find("h4", string=re.compile("Nutrition", re.I)).find_next_sibling()

	rows = nutrition_table.find_all("tr")

	nutrition_data = []

	for row in rows:
	    cells = row.find_all(["td", "th"])
	    values = [cell.get_text(strip=True) for cell in cells]
	    nutrition_data.append(values)


#headers = table_data[0]
#data = table_data[1:]

	if nutrition_data != None:
		nutrition = {}
		
		for i in nutrition_data:
			for j in range(len(i)):
				i[j] = i[j].replace("\\r", "").replace("\\n", "")
		
		for i in nutrition_data:
			if i[0] == '':
				nutrition['units'] = i[1:]
			
			else:
				nutrition[i[0]] = i[1:]

		return nutrition

	else:
		return False


currentTable = openpyxl.load_workbook(CURRENT_TABLE_FILE)
currentTableSheet = currentTable.active


#, per 100 ml, per Ampoulle (25 ml)
#Energie (kcal), 1223 (288), 306 (72)
#Fett, 0 g, 0 g
#davon gesättigte Fettsäuren, 0 g, 0 g
#Kohlenhydrate, 18.2 g, 4.6 g
#davon Zuckerarten, 17.8 g, 4.4 g
#Ballaststoffe, 0 g, 0 g # Fibres
#Protein, 50 g, 12.5 g
#Salz **, 0.18 g, 0.05 g
#
#
#
#, per 100 g, per 100 ml (25 g)
#energy kJ (kcal), 1660 (390), 410 (96)
#fat, 0 g, 0 g
#of which saturated fatty acids, 0 g, 0 g
#carbohydrates, 97 g, 24 g
#of which sugars, 56 g, 14 g
#protein, 0 g, 0 g
#salt **, 0.53 g, 0.13 g





newTable = openpyxl.Workbook()
newTableSheet = newTable.active

titles = currentTableSheet["A1":"K1"]
for title in titles[0]:
	newTableSheet[title.coordinate].value = title.value

for row in currentTableSheet.iter_rows(min_row=2,max_row=3):
	nutrition_cell = "C{}".format(row[0].row)
	nutrition_data = ExtractNutrition(currentTableSheet[nutrition_cell].value)
	print(nutrition_data)
	for cell in row:
		if cell.column_letter == "A" or cell.column_letter == "B":
			newTableSheet[cell.coordinate] = cell.value
		else:
			if nutrition_data == False:
				if nutrition_data['units'] > 1:
					for i in range(len(nutrition_data['units'])-1):
						



newTable.save(NEW_TABLE_FILE)
